using Cognas.ApiTools.BusinessLogic;
using Cognas.ApiTools.Mapping;
using Cognas.ApiTools.MinimalApi;
using Cognas.ApiTools.Pagination;
using Cognas.ApiTools.Shared;
using Microsoft.Extensions.Logging;

namespace {0};

/// <summary>
/// Auto generated by decoration using <see cref="Cognas.ApiTools.SourceGenerators.Attributes.QueryScaffoldAttribute"/>.
/// </summary>
#nullable enable
public sealed partial class {1}QueryApi : QueryApiBase<{2}, {3}>
{{
    #region Constructor / Finaliser Declarations

    /// <summary>
    /// Default constructor for <see cref="{1}QueryApi"/>
    /// </summary>
    /// <param name="logger"></param>
    /// <param name="queryMappingService"></param>
    /// <param name="modelIdService"></param>
    /// <param name="paginationFunctions"></param>
    /// <param name="queryBusinessLogic"></param>
    public {1}QueryApi
    (
        ILogger<{1}QueryApi> logger,
        IQueryMappingService<{2}, {3}> queryMappingService,
        IModelIdService modelIdService,
        IPaginationFunctions paginationFunctions,
        IQueryBusinessLogic<{2}> queryBusinessLogic
    )
    : base(logger, queryMappingService, modelIdService, paginationFunctions, queryBusinessLogic)
    {{
    }}

    #endregion
}}