using Cognas.ApiTools.BusinessLogic;
using Cognas.ApiTools.Data.Query;
using Cognas.ApiTools.Shared;
using Microsoft.Extensions.Caching.Memory;
using Model = {0};

namespace {1}.v{2};

/// <summary>
/// Auto generated by decoration using <see cref="Cognas.ApiTools.SourceGenerators.Attributes.QueryScaffoldAttribute"/>.
/// </summary>
#nullable enable
public sealed partial class {3}QueryBusinessLogic : QueryBusinessLogicBase<Model>
{{
    #region Constructor / Finaliser Declarations

    /// <summary>
    /// Default constructor for <see cref="{3}QueryBusinessLogic"/>
    /// </summary>
    /// <param name="logger"></param>
    /// <param name="memoryCache"></param>
    /// <param name="modelIdService"></param>
    /// <param name="databaseService"></param>
    public {3}QueryBusinessLogic
    (
        ILogger<{3}QueryBusinessLogic> logger,
        IMemoryCache memoryCache,
        IModelIdService modelIdService,
        IQueryDatabaseService databaseService
    )
    : base(logger, memoryCache, modelIdService, databaseService)
    {{
    }}

    #endregion
}}