using Cognas.ApiTools.BusinessLogic;
using Cognas.ApiTools.Data.Query;
using Cognas.ApiTools.Shared;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.Logging;

namespace {0};

/// <summary>
/// Auto generated by decoration using <see cref="Cognas.ApiTools.SourceGenerators.Attributes.QueryScaffoldAttribute"/>.
/// </summary>
#nullable enable
public sealed partial class {1}QueryBusinessLogic : QueryBusinessLogicBase<{2}>
{{
    #region Constructor / Finaliser Declarations

    /// <summary>
    /// Default constructor for <see cref="{1}QueryBusinessLogic"/>
    /// </summary>
    /// <param name="logger"></param>
    /// <param name="memoryCache"></param>
    /// <param name="modelIdService"></param>
    /// <param name="databaseService"></param>
    public {1}QueryBusinessLogic
    (
        ILogger<{1}QueryBusinessLogic> logger,
        IMemoryCache memoryCache,
        IModelIdService modelIdService,
        IQueryDatabaseService databaseService
    )
    : base(logger, memoryCache, modelIdService, databaseService)
    {{
    }}

    #endregion
}}