using Cognas.ApiTools.Mapping;
using Model = {0};
using Response = {1};

namespace {2}.v{3};

/// <summary>
/// Auto generated by decoration using <see cref="Cognas.ApiTools.SourceGenerators.Attributes.CommandScaffoldAttribute"/>.
/// </summary>
#nullable enable
public sealed partial class {4}QueryMappingService : QueryMappingServiceBase<Model, Response>
{{
    #region Constructor / Finaliser Declarations

    /// <summary>
    /// Default constructor for <see cref="{4}QueryMappingServic"/>
    /// </summary>
    public {4}QueryMappingService()
    {{
    }}

    #endregion

    #region Public Method Declarations

    /// <summary>
    /// 
    /// </summary>
    /// <param name="model"></param>
    /// <returns></returns>
    public override Response ModelToResponse(Model model)
    {{
        Response response = new()
        {{
{5}
        }};
        return response;
    }}

    #endregion
}}