using Cognas.ApiTools.BusinessLogic;
using Cognas.ApiTools.Mapping;
using Cognas.ApiTools.MinimalApi;
using Cognas.ApiTools.Pagination;
using Cognas.ApiTools.Shared;
using Model = {0};
using Response = {1};

namespace {2}.v{3};

/// <summary>
/// Auto generated by decoration using <see cref="Cognas.ApiTools.SourceGenerators.Attributes.QueryScaffoldAttribute"/>.
/// </summary>
#nullable enable
public sealed partial class {4}QueryApi : QueryApiBase<Model, Response>
{{
    #region Property Declarations

    /// <summary>
    /// 
    /// </summary>
    public override int ApiVersion => {3};

    #endregion

    #region Constructor / Finaliser Declarations

    /// <summary>
    /// Default constructor for <see cref="{4}QueryApi"/>
    /// </summary>
    /// <param name="logger"></param>
    /// <param name="queryMappingService"></param>
    /// <param name="modelIdService"></param>
    /// <param name="paginationFunctions"></param>
    /// <param name="queryBusinessLogic"></param>
    public {4}QueryApi
    (
        ILogger<{4}QueryApi> logger,
        IQueryMappingService<Model, Response> queryMappingService,
        IModelIdService modelIdService,
        IPaginationFunctions paginationFunctions,
        IQueryBusinessLogic<Model> queryBusinessLogic
    )
    : base(logger, queryMappingService, modelIdService, paginationFunctions, queryBusinessLogic)
    {{
    }}

    #endregion
}}