using Cognas.ApiTools.BusinessLogic;
using Cognas.ApiTools.Mapping;
using Cognas.ApiTools.MinimalApi;
using Cognas.ApiTools.Shared;
using Microsoft.Extensions.Logging;

namespace {0};

/// <summary>
/// Auto generated by decoration using <see cref="Cognas.ApiTools.SourceGenerators.Attributes.CommandScaffoldAttribute"/>.
/// </summary>
#nullable enable
public sealed partial class {1}CommandApi : CommandApiBase<{2},{3},{4}>
{{
    #region Constructor / Finaliser Declarations

    /// <summary>
    /// Default constructor for <see cref="{1}CommandApi"/>
    /// </summary>
    /// <param name="logger"></param>
    /// <param name="mappingService"></param>
    /// <param name="modelIdService"></param>
    /// <param name="commandBusinessLogic"></param>
    public {1}CommandApi
    (
        ILogger<{1}CommandApi> logger,
        ICommandMappingService<{2},{3},{4}> mappingService,
        IModelIdService modelIdService,
        ICommandBusinessLogic<{2}> commandBusinessLogic
    )
    : base(logger, mappingService, modelIdService, commandBusinessLogic)
    {{
    }}

    #endregion
}}