using Cognas.ApiTools.BusinessLogic;
using Cognas.ApiTools.Data.Command;
using Cognas.ApiTools.Messaging;
using Cognas.ApiTools.Shared;
using Model = {0};

namespace {1}.v{2};

/// <summary>
/// Auto generated by decoration using <see cref="Cognas.ApiTools.SourceGenerators.Attributes.CommandScaffoldAttribute"/>.
/// </summary>
#nullable enable
public sealed partial class {3}CommandBusinessLogic : CommandBusinessLogicBase<Model>
{{
    #region Constructor / Finaliser Declarations

    /// <summary>
    /// Default constructor for <see cref="{3}CommandBusinessLogic"/>
    /// </summary>
    /// <param name="logger"></param>
    /// <param name="modelIdService"></param>
    /// <param name="databaseService"></param>
    /// <param name="messagingService"></param>
    public {3}CommandBusinessLogic
    (
        ILogger<{3}CommandBusinessLogic> logger,
        IModelIdService modelIdService,
        ICommandDatabaseService databaseService,
        IModelMessagingService<Model> messagingService
    )
    : base(logger, modelIdService, databaseService, messagingService)
    {{
    }}

    #endregion
}}